// synappseV2/api/firebase-config.js
// This is a Vercel Serverless Function that serves your Firebase configuration
// from environment variables to the client-side.
// It ensures your Firebase config values are not hardcoded in the client bundle

export default function handler(request, response) {
  // Set the Content-Type header to 'application/javascript'
  // so the browser interprets this response as a JavaScript file.
  response.setHeader('Content-Type', 'application/javascript');

  // Set Cache-Control headers for optimal performance.
  // 'max-age=0, must-revalidate' ensures the browser always re-fetches
  // this file from the server, which is good for configuration that might change.
  response.setHeader('Cache-Control', 'max-age=0, must-revalidate');

  // Send a 200 OK status.
  response.status(200).send(`
    // This JavaScript snippet defines a global 'window.firebaseConfig' object.
    // It is dynamically generated by the Vercel serverless function,
    // pulling values directly from your Vercel environment variables.
    // This script should be loaded in your index.html BEFORE firebase-init.js.
    window.firebaseConfig = {
      apiKey: "${process.env.FIREBASE_API_KEY || ''}",
      authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || ''}",
      projectId: "${process.env.FIREBASE_PROJECT_ID || ''}",
      storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
      messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
      appId: "${process.env.FIREBASE_APP_ID || ''}",
      measurementId: "${process.env.FIREBASE_MEASUREMENT_ID || ''}"
    };
  `);
}

